language: python
python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"

script:
  - sudo apt-get install pandoc
  - python setup.py install
  - pytest -s test/
  - python setup.py sdist