language: python
cache: pip
python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

script:
  - sudo apt-get install pandoc
  - python -m pip install --upgrade pip
  - pip install .
  - pytest -s test/
  - python setup.py sdist