language: python
cache: pip
python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

script:
  - sudo apt-get install pandoc
  - pip install -r test/requirements.txt
  - python setup.py install
  - pytest -s test/
  - python setup.py sdist